# Generated by Django 5.2.3 on 2025-07-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
